import { FormEvent, useState } from "react";
import { AlertTriangle, Download, Loader2, Microscope, Play } from "lucide-react";
import { api, ApiError } from "../../api/client";
import { ModuleBanner } from "../../components/ModuleBanner";
import { ProfileChart } from "../../components/ProfileChart";

type Result = {run_id:number; engine_version:string; bcs:{class:string; solubility_class:string; permeability_class:string; solubility_mg_per_ml:number; dose_volume_ml:number; formulation_note:string}; metrics:{sink_conditions:boolean; final_dissolved_percent:number; saturation_solubility_mg_ml:number; diffusion_coefficient_cm2_s:number}; profile:{time_min:number; dissolved_percent:number}[]; warnings:string[]};
const initial = {dose_mg:"100", molecular_weight:"250.2", log_s:"-3.1", hia_percent:"92", particle_diameter_um:"50", drug_density_g_cm3:"1.2", medium_volume_ml:"900", boundary_layer_um:"30", duration_min:"120", output_points:"30"};

function Field({label, unit, value, onChange, step="any"}:{label:string;unit?:string;value:string;onChange:(v:string)=>void;step?:string}) { return <label className="block"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</span><div className="mt-1.5 flex overflow-hidden rounded-lg border border-slate-300 bg-white focus-within:border-cyan-500 focus-within:ring-4 focus-within:ring-cyan-50"><input required type="number" step={step} value={value} onChange={e=>onChange(e.target.value)} className="min-w-0 flex-1 px-3 py-2.5 text-sm"/>{unit && <span className="grid place-items-center border-l border-slate-200 bg-slate-50 px-3 text-xs text-slate-500">{unit}</span>}</div></label> }

export function DissolutionPage() {
  const [form,setForm] = useState(initial); const [result,setResult] = useState<Result|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const set=(key:keyof typeof form)=>(value:string)=>setForm(v=>({...v,[key]:value}));
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");try{const payload=Object.fromEntries(Object.entries(form).map(([k,v])=>[k,k==="hia_percent"&&v===""?null:Number(v)]));setResult(await api.simulateDissolution<Result>(payload));}catch(e){setError(e instanceof ApiError?e.message:"Simulation failed unexpectedly.");}finally{setLoading(false);}}
  function download(){if(!result)return;const csv=["time_min,dissolved_percent",...result.profile.map(p=>`${p.time_min},${p.dissolved_percent}`)].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download=`dissolution-run-${result.run_id}.csv`;link.click();URL.revokeObjectURL(url);}
  return <div className="min-h-screen bg-slate-50 px-4 py-5 sm:px-6 lg:px-8 lg:py-8">
    <div className="mx-auto max-w-[1500px]">
    <ModuleBanner icon={Microscope} eyebrow="Formulation sciences" title="Dissolution Behavior Prediction" description="Model dissolution profiles, assess sink conditions, and review formulation implications using transparent scientific inputs."/>
    <div className="mt-6 grid gap-6 xl:grid-cols-[390px_1fr]">
      <form onSubmit={submit} className="self-start rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><div><h2 className="font-bold text-navy-950">Simulation inputs</h2><p className="mt-1 text-sm text-slate-500">Noyes–Whitney particle population model</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2">
        <Field label="Dose" unit="mg" value={form.dose_mg} onChange={set("dose_mg")}/><Field label="Molecular weight" unit="g/mol" value={form.molecular_weight} onChange={set("molecular_weight")}/><Field label="LogS" value={form.log_s} onChange={set("log_s")}/><Field label="HIA" unit="%" value={form.hia_percent} onChange={set("hia_percent")}/><Field label="Particle diameter" unit="µm" value={form.particle_diameter_um} onChange={set("particle_diameter_um")}/><Field label="Drug density" unit="g/cm³" value={form.drug_density_g_cm3} onChange={set("drug_density_g_cm3")}/><Field label="Medium volume" unit="mL" value={form.medium_volume_ml} onChange={set("medium_volume_ml")}/><Field label="Boundary layer" unit="µm" value={form.boundary_layer_um} onChange={set("boundary_layer_um")}/><Field label="Duration" unit="min" step="1" value={form.duration_min} onChange={set("duration_min")}/><Field label="Output points" step="1" value={form.output_points} onChange={set("output_points")}/></div>
        {error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg bg-cyan-600 px-4 py-3 font-semibold text-white hover:bg-cyan-700 disabled:opacity-60">{loading?<Loader2 className="animate-spin" size={18}/>:<Play size={18}/>} Run simulation</button>
      </form>
      <section className="min-w-0 space-y-6">
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["BCS class",result?.bcs.class??"—"],["Final dissolved",result?`${result.metrics.final_dissolved_percent}%`:"—"],["Sink conditions",result?(result.metrics.sink_conditions?"Yes":"No"):"—"],["Run ID",result?`#${result.run_id}`:"—"]].map(([label,value])=><div key={label} className="rounded-xl border border-slate-200 bg-white p-4 shadow-panel"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 text-xl font-bold text-navy-950">{value}</p></div>)}</div>
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><div className="flex items-center justify-between"><div><h2 className="font-bold text-navy-950">Predicted dissolution profile</h2><p className="mt-1 text-sm text-slate-500">Percent dissolved over simulated time</p></div><button onClick={download} disabled={!result} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50 disabled:opacity-40"><Download size={16}/> Export CSV</button></div><div className="mt-4"><ProfileChart data={result?.profile??[]}/></div></div>
        {result&&<div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><h3 className="font-bold text-navy-950">Classification</h3><dl className="mt-4 grid gap-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-slate-500">Solubility</dt><dd className="font-semibold">{result.bcs.solubility_class}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Permeability</dt><dd className="font-semibold">{result.bcs.permeability_class}</dd></div><div className="flex justify-between gap-4"><dt className="text-slate-500">Saturation solubility</dt><dd className="font-semibold">{result.metrics.saturation_solubility_mg_ml.toExponential(3)} mg/mL</dd></div></dl><p className="mt-4 rounded-lg bg-cyan-50 p-3 text-sm leading-6 text-cyan-900">{result.bcs.formulation_note}</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="flex items-center gap-2 font-bold text-amber-900"><AlertTriangle size={18}/> Model limitations</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-amber-900">{result.warnings.map(w=><li key={w}>• {w}</li>)}</ul></div></div>}
      </section>
    </div>
    </div>
  </div>;
}
