import { AlertTriangle, BookOpen, CheckCircle2, FlaskConical, LoaderCircle, Search, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { ApiError, api } from "../../api/client";
import { ModuleBanner } from "../../components/ModuleBanner";

type Excipient={name:string;cas:string;formula:string;category:string;synonyms:string};
type Rule={excipient:string;drug_groups:string[];reaction_type:string;risk:"Low"|"Medium"|"High";description:string};
type Result={drug_profile:{name:string;smiles:string;molecular_weight:number|null;functional_groups:string[]};excipient_profiles:(Excipient&{name:string})[];recommended_risk:"Low"|"Medium"|"High";rule_based_evidence:Rule[];pubmed_evidence:{excipient:string;pmid:string;title:string;journal:string;date:string;url:string}[];warnings:string[]};
const riskStyle={Low:"border-emerald-200 bg-emerald-50 text-emerald-700",Medium:"border-amber-200 bg-amber-50 text-amber-700",High:"border-rose-200 bg-rose-50 text-rose-700"};

export function CompatibilityPage(){
 const [catalog,setCatalog]=useState<Excipient[]>([]);const [apiInput,setApiInput]=useState("");const [selected,setSelected]=useState<string[]>([]);const [includePubmed,setIncludePubmed]=useState(true);const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{void api.excipientCatalog<{excipients:Excipient[]}>().then(x=>setCatalog(x.excipients)).catch(()=>setError("Could not load the local excipient catalogue."))},[]);
 const message=(e:unknown)=>e instanceof ApiError?e.message:"Request could not be completed.";
 async function screen(){if(apiInput.trim().length<2)return setError("Enter an API name or SMILES structure.");if(!selected.length)return setError("Select one or more excipients.");setBusy(true);setError("");try{setResult(await api.runCompatibility<Result>({api_input:apiInput,excipients:selected,include_pubmed:includePubmed}))}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <div className="min-h-screen bg-slate-50 px-4 py-5 sm:px-6 lg:px-8 lg:py-8"><div className="mx-auto max-w-[1500px]">
  <ModuleBanner icon={FlaskConical} eyebrow="Preformulation Science" title="Drug–Excipient Compatibility" description="Screen formulation excipients against an API structure using transparent functional-group rules and optional PubMed title matches."/>
  {error&&<div className="mt-5 flex gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"><AlertTriangle size={18}/>{error}</div>}
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div><label className="text-xs font-semibold uppercase tracking-wide text-slate-500">Active pharmaceutical ingredient</label><input value={apiInput} onChange={e=>setApiInput(e.target.value)} placeholder="e.g., Clopidogrel Bisulfate or SMILES" className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 text-sm focus:border-emerald-500"/><label className="mt-4 flex items-start gap-2 text-xs leading-5 text-slate-600"><input type="checkbox" checked={includePubmed} onChange={e=>setIncludePubmed(e.target.checked)} className="mt-1"/>Search PubMed for title matches. This sends the API and excipient names to NCBI; no proprietary formulation data is sent.</label><button onClick={()=>void screen()} disabled={busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-60">{busy?<LoaderCircle className="animate-spin" size={17}/>:<Search size={17}/>}Run compatibility screening</button></div>
  <div><div className="flex items-center justify-between"><label className="text-xs font-semibold uppercase tracking-wide text-slate-500">Select excipients</label><span className="text-xs text-slate-500">{selected.length} selected</span></div><div className="mt-2 grid max-h-56 gap-2 overflow-y-auto rounded-xl border border-slate-200 p-3 sm:grid-cols-2">{catalog.map(item=><label key={item.name} className={`flex cursor-pointer items-start gap-2 rounded-lg border p-2 text-xs leading-4 ${selected.includes(item.name)?"border-emerald-300 bg-emerald-50":"border-transparent hover:bg-slate-50"}`}><input type="checkbox" checked={selected.includes(item.name)} onChange={()=>setSelected(s=>s.includes(item.name)?s.filter(x=>x!==item.name):[...s,item.name])} className="mt-0.5"/><span><strong className="block text-slate-800">{item.name}</strong><span className="text-slate-500">{item.category}</span></span></label>)}</div></div></div></section>
  {!result?<div className="mt-6 grid min-h-64 place-items-center rounded-2xl border-2 border-dashed border-slate-200 bg-white text-center text-sm text-slate-500">Run a screen to view API profile, rule-based risks, and PubMed matches.</div>:<section className="mt-6 space-y-6"><div className="grid gap-6 lg:grid-cols-[1fr_1.35fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><div className="flex items-center justify-between"><h2 className="font-bold text-navy-900">Drug profile</h2><span className={`rounded-full border px-3 py-1 text-xs font-bold ${riskStyle[result.recommended_risk]}`}>{result.recommended_risk} risk</span></div><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs font-semibold text-slate-500">Resolved identity</dt><dd className="mt-1 text-slate-800">{result.drug_profile.name}</dd></div><div><dt className="text-xs font-semibold text-slate-500">Molecular weight</dt><dd className="mt-1 text-slate-800">{result.drug_profile.molecular_weight??"Not resolved"}</dd></div><div><dt className="text-xs font-semibold text-slate-500">Detected functional groups</dt><dd className="mt-1 flex flex-wrap gap-1">{result.drug_profile.functional_groups.length?result.drug_profile.functional_groups.map(g=><span key={g} className="rounded-full bg-slate-100 px-2 py-1 text-xs text-slate-700">{g}</span>):<span className="text-slate-500">Not resolved</span>}</dd></div></dl></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><h2 className="font-bold text-navy-900">Rule-based evidence</h2><div className="mt-4 space-y-3">{result.rule_based_evidence.map((rule,i)=><div key={i} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-slate-800">{rule.excipient}</p><span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${riskStyle[rule.risk]}`}>{rule.risk}</span></div><p className="mt-2 text-sm font-medium text-navy-900">{rule.reaction_type}</p><p className="mt-1 text-sm leading-6 text-slate-600">{rule.description}</p></div>)}</div></div></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><h2 className="font-bold text-navy-900">Excipient profiles</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{result.excipient_profiles.map(p=><div key={p.name} className="rounded-xl border border-slate-200 p-4 text-sm"><p className="font-semibold text-slate-800">{p.name}</p><p className="mt-2 text-xs text-slate-500">CAS {p.cas} · {p.formula}</p><p className="mt-1 text-xs text-emerald-700">{p.category}</p></div>)}</div></div>
  <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-panel"><div className="flex items-center gap-2"><BookOpen size={18} className="text-cyan-700"/><h2 className="font-bold text-navy-900">PubMed title matches</h2></div>{!result.pubmed_evidence.length?<p className="mt-4 text-sm text-slate-500">No title matches were returned. A missing match does not establish compatibility.</p>:<div className="mt-4 space-y-2">{result.pubmed_evidence.map(p=><a key={p.pmid+p.excipient} href={p.url} target="_blank" rel="noreferrer" className="block rounded-lg border border-slate-200 p-3 hover:border-cyan-300"><p className="text-sm font-medium text-navy-900">{p.title}</p><p className="mt-1 text-xs text-slate-500">{p.excipient} · {p.journal} · {p.date} · PMID {p.pmid}</p></a>)}</div>}</div>
  <div className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs leading-5 text-amber-900"><ShieldCheck className="shrink-0" size={17}/>{result.warnings.join(" ")}</div></section>}
 </div></div>
}
